# Week 2 - Klasifikasi MNIST dengan softmax
Marvel Kevin Nathanael | 00000108042

Satu Dense layer sebagai baseline regresi logistik multikelas sesuai TLM 2.

In [1]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

tf.keras.utils.set_random_seed(42)
(x_dev, y_dev), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_dev = x_dev.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0
x_train, x_val, y_train, y_val = train_test_split(
    x_dev, y_dev, test_size=0.1, random_state=42, stratify=y_dev)
model = tf.keras.Sequential([
    tf.keras.Input(shape=(28, 28)), tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation="softmax")
])
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])
history = model.fit(x_train, y_train, validation_data=(x_val, y_val),
                    epochs=15, batch_size=128, verbose=0,
                    callbacks=[tf.keras.callbacks.EarlyStopping(
                        monitor="val_loss", patience=3, restore_best_weights=True)])

In [2]:
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
y_pred = np.argmax(model.predict(x_test, verbose=0), axis=1)
print(f"Test accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred, digits=3))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Test accuracy: 0.9262
              precision    recall  f1-score   support

           0      0.947     0.984     0.965       980
           1      0.969     0.982     0.976      1135
           2      0.938     0.891     0.914      1032
           3      0.903     0.917     0.910      1010
           4      0.936     0.927     0.931       982
           5      0.895     0.882     0.889       892
           6      0.946     0.949     0.947       958
           7      0.927     0.927     0.927      1028
           8      0.885     0.884     0.884       974
           9      0.906     0.910     0.908      1009

    accuracy                          0.926     10000
   macro avg      0.925     0.925     0.925     10000
weighted avg      0.926     0.926     0.926     10000

Confusion matrix:
 [[ 964    0    1    2    0    5    5    2    1    0]
 [   0 1115    3    2    0    1    4    2    8    0]
 [   7    9  919   18    6    5   13   11   40    4]
 [   4    0   15  926    0   26    2   11

**Catatan:** Output softmax sudah berupa probabilitas, sehingga loss tidak memakai from_logits=True. Periksa confusion matrix untuk kesalahan per digit.